### ISSUE TITLE
change url sosmed in footer

### ISSUE THREAD

**Issue by Farrasai** [jugosx/festacap.id#9]
![2](https://user-images.githubusercontent.com/26664613/60273074-7e174180-991f-11e9-862e-be4f59eee4a6.JPG)

kie mad ganti https://twitter.com/festacap2019

**Comment by jugosx** [comment]
Itu yang EMAIL/WHATSAPP mau diapain mas ?

**Comment by Farrasai** [comment]
buang bae ganti email awkwkwkowk

**Comment by Farrasai** [comment]
asikk juga nih komentar bisa jadi medsos baruq

**Comment by jugosx** [comment]
Done

**Comment by Farrasai** [comment]
sante  ae kang aja kaku bgt komene wkwk emote langka kie apa
